import{i as u,S as m}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const p="42557363-2349d8dc8525cd1cea516a01b",d="https://pixabay.com/api/",f="",c=document.querySelector("#form"),i=document.querySelector(".loader"),l=document.querySelector(".gallery"),y={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.9,scaleImageToRatio:!0};i.style.display="none";document.addEventListener("DOMContentLoaded",()=>{c.addEventListener("submit",o=>{o.preventDefault();const r=document.getElementById("search").value.trim();if(!r)return;i.style.display="inline-block",l.innerHTML="";const n=new URLSearchParams({key:p,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}),e=`${d}${f}?${n}`;fetch(e).then(t=>t.json()).then(t=>a(t)).catch(t=>{console.error("Error fetching data:",t)}).finally(()=>{i.style.display="none"})});function a(o){if(o.hits.length===0)u.error({title:"",backgroundColor:"#EF4040",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{const r=o.hits.map(e=>`<li class="gallery-item"><a href="${e.webformatURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
          <div class='comments'>
          <p><b>Likes: </b>${e.likes}</p>
          <p><b>Views: </b>${e.views}</p>
          <p><b>Comments: </b>${e.comments}</p>
          <p><b>Downloads: </b>${e.downloads}</p>
          </div>
          </li>`).join("");l.insertAdjacentHTML("afterbegin",r),new m(".gallery a",y).refresh(),c.reset()}}});
//# sourceMappingURL=commonHelpers.js.map
